server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8901/eureka/
  instance:
    instance-id: consumers
    prefer-ip-address: true

info:
  app.name: mySpringCloud
  author: zxa
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: consumers
