server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://120.79.225.94:8901/eureka/
  instance:
    instance-id: control-center
    prefer-ip-address: true

info:
  appName: mySpringCloud
  author: zxa
  build.artifactId: @project.artifactId@
  build.version: @project.version@
spring:
  application:
    name: control-center

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true                 #开启feign的hystrix功能

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000