server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8901/eureka/
  instance:
    instance-id: controlCenter
    prefer-ip-address: true

info:
  appName: mySpringCloud
  author: zxa
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: controlCenter

ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000