spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rain-Raven/spring-cloud-config.git
          username: Rain-Raven
          password: jpygithub0708
          default-label: master

server:
  port: 8888
logging:
  file: /root/spring-cloud/log/${spring.application.name}-log
  level:
    com.zxa: warn
